# These are supported funding model platforms

github: [themobileprof]
# patreon: # your-patreon
# open_collective: # your-open-collective
# ko_fi: # your-ko-fi
# tidelift: # npm/package-name
# community_bridge: # your-community-bridge
# liberapay: # your-liberapay
# issuehunt: # your-issuehunt
# otechie: # your-otechie
# lfx_crowdfunding: # your-lfx-crowdfunding
# custom: # your-custom-url
